server.port=8083

spring.application.name=rendezvous-service

spring.datasource.url=jdbc:mariadb://localhost:3306/rendezvous_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

patients.service.url=http://172.20.10.5:8081
medecins.service.url=http://172.20.10.7:8085
planning.service.url=http://172.20.10.6:9090
notifications.service.url=http://192.168.1.35:8086

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
