server.port=${SERVER_PORT:8084}

spring.application.name=dossiers-service

spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/dossiers_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URLs of other microservices
patients.service.url=${PATIENTS_SERVICE_URL:http://localhost:8081}
rendezvous.service.url=${RENDEZVOUS_SERVICE_URL:http://localhost:8083}
medecins.service.url=${MEDECINS_SERVICE_URL:http://localhost:8082}
notifications.service.url=${NOTIFICATIONS_SERVICE_URL:http://localhost:8085}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
